on: [push]

jobs:
  ansible_job:
    runs-on: ubuntu-latest
    name: A job to execute ansible
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Ansible action step
      uses: ./
      id: ansible
      with:
        playbook: site.yml
    - name: Get the output
      run: echo "${{ steps.ansible.outputs.output }}"